formatter: "markdown table" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    ### Execute Terragrunt  
    #### Setup Provider
    ```
    export AWS_ACCESS_KEY_ID=[YOUR_ACCESS_KEY_HERE]
    export AWS_SECRET_ACCESS_KEY=[YOUR_SECRET_ACCESS_KEY_HERE]
    export AWS_REGION=[YOUR_REGION_HERE]
    ```
    #### Setup Terragrunt 
    ```
    terragrunt init
    ```
    #### Apply Terragrunt
    ```
    terragrunt apply -target=module.vpc -target=module.igw -target=module.eip
    terragrunt apply -target=module.nat
    ```
      {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
